#! /usr/bin/env bash

if [ $# -ne 2 ]; then
    echo " usage: $0 [device] [on|off] "
    exit 1
fi   
dev=$1
cmd=$2

ch=$(awk -v dev="$dev" '$1==dev{print $2}' /emmi/system/gude/gude.conf)
if [ -z "$ch" ]; then
    echo " invalid device: ${dev}"
    exit 1
fi

case "$cmd" in
    on)  s=1 ;;
    off) s=0 ;;
    *) echo " invalid command: ${cmd}"; exit 1 ;;
esac

echo " --- switching Gude ${dev} ${cmd} "
curl -sS "http://gude-1202/?cmd=1&p=${ch}&s=${s}" -o /dev/null && echo " switched ${dev} ${cmd} "
